USE Teamify_Draft3
CREATE TABLE USER_TYPE (
	UserTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	UserTypeName VARCHAR(50) NOT NULL,
	UserTypeDescr VARCHAR(1000)
)
GO

CREATE TABLE [USER] (
	UserID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	MiddleName VARCHAR(50),
	LastName VARCHAR(50) NOT NULL,
	BirthDate DATE NOT NULL,
	eMail VARCHAR(100) NOT NULL,
	UserBeginDate DATE NOT NULL,
	UserTypeID INT FOREIGN KEY REFERENCES USER_TYPE(UserTypeID) NOT NULL
)
GO

CREATE TABLE INSTITUTION_TYPE(
	InstitutionTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	InstitutionTypeName VARCHAR(50) NOT NULL,
	InstitutionTypeDescr VARCHAR(1000)
)
GO

CREATE TABLE INSTITUTION(
	InstitutionID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	InstitutionName VARCHAR(50) NOT NULL,
	InstitutionTypeID INT FOREIGN KEY REFERENCES INSTITUTION_TYPE(InstitutionTypeID) NOT NULL,
	InstitutionBeginDate DATE NOT NULL,
	InstitutionDescr VARCHAR(1000)
)
GO

CREATE TABLE GROUP_TYPE(
	GroupTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	GroupTypeName VARCHAR(50) NOT NULL,
	GroupTypeDescr VARCHAR(1000)
)
GO

CREATE TABLE [GROUP](
	GroupID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	GroupName VARCHAR(50) NOT NULL,
	GroupDescr VARCHAR(1000),
	GroupBeginDate DATE NOT NULL,
	GroupTypeID INT FOREIGN KEY REFERENCES GROUP_TYPE(GroupTypeID) NOT NULL,
	InstitutionID INT FOREIGN KEY REFERENCES INSTITUTION(InstitutionID) NOT NULL,
	ParentGroupID INT FOREIGN KEY REFERENCES [GROUP](GroupID)
	
)
GO

CREATE TABLE TEAM_TYPE(
	TeamTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TeamTypeName VARCHAR(50) NOT NULL,
	TeamTypeDescr VARCHAR(1000)
)
GO

CREATE TABLE TEAM (
	TeamID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TeamName VARCHAR(50) NOT NULL,
	TeamBeginDate DATE NOT NULL,
	TeamTypeID INT FOREIGN KEY REFERENCES TEAM_TYPE(TeamTypeID) NOT NULL,
	TeamDescr VARCHAR(1000)
)
GO

CREATE TABLE PROJECT_TYPE(
	ProjectTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ProjectTypeName VARCHAR(50) NOT NULL,
	ProjectTypeDescr VARCHAR(1000)
)
GO

CREATE TABLE PROJECT(
	ProjectID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ProjectName VARCHAR(50) NOT NULL,
ProjectDescr VARCHAR(1000),
	ProjectTypeID INT FOREIGN KEY REFERENCES PROJECT_TYPE(ProjectTypeID) NOT NULL,
	ProjectBeginDate DATE NOT NULL,
	GroupID INT FOREIGN KEY REFERENCES [GROUP](GroupID) NOT NULL
)
GO

CREATE TABLE PROJECT_TEAM (
	ProjectTeamID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ProjectID INT FOREIGN KEY REFERENCES PROJECT(ProjectID) NOT NULL,
	TeamID INT FOREIGN KEY REFERENCES TEAM(TeamID) NOT NULL
)
GO

CREATE TABLE [ROLE](
	RoleID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	RoleName VARCHAR(50) NOT NULL,
RoleDescr VARCHAR(1000)
)
GO

CREATE TABLE USER_TEAM_ROLE(
	UserTeamRoleID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	UserID INT FOREIGN KEY REFERENCES [USER](UserID) NOT NULL,
	TeamID INT FOREIGN KEY REFERENCES TEAM(TeamID) NOT NULL,
RoleID INT FOREIGN KEY REFERENCES ROLE(RoleID) NOT NULL,
UTRBeginDate DATE NOT NULL
)
GO

CREATE TABLE TASK_TYPE(
	TaskTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TaskTypeName VARCHAR(50) NOT NULL,
TaskTypeDescr VARCHAR(1000)
)
GO

CREATE TABLE TASK (
	TaskID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TaskName VARCHAR(50) NOT NULL,
	TaskDescr VARCHAR(1000),
	TaskTypeID INT FOREIGN KEY REFERENCES TASK_TYPE(TaskTypeID) NOT NULL,
	JobID INT FOREIGN KEY REFERENCES TASK(TaskID)
)

CREATE TABLE PROJECT_TASK(
	ProjectTaskID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ProjectID INT FOREIGN KEY REFERENCES PROJECT(ProjectID) NOT NULL,
TaskID INT FOREIGN KEY REFERENCES TASK(TaskID) NOT NULL,
	ProjectTaskDate DATE NOT NULL
)

CREATE TABLE ACTION(
	ActionID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ActionName VARCHAR(50) NOT NULL,
ActionDescr VARCHAR(1000)
)
GO

CREATE TABLE USER_TEAM_ROLE_ACTION_TASK(
	UTRAT_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	UserTeamRoleID INT FOREIGN KEY REFERENCES USER_TEAM_ROLE(UserTeamRoleID) NOT NULL,
	TaskID INT FOREIGN KEY REFERENCES TASK(TaskID)  NOT NULL,
	ActionID INT FOREIGN KEY REFERENCES [ACTION](ActionID)  NOT NULL,
	UTRATBeginDate DATE NOT NULL,
	UTRATDueDate DATE NOT NULL,
	Points NUMERIC(5,2) NOT NULL
)
GO

CREATE TABLE EVENT_TYPE (
	EventTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	EventTypeName VARCHAR(50) NOT NULL,
	EventTypeDescr VARCHAR(1000) 
)
GO

CREATE TABLE [EVENT] (
	EventID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	EventName VARCHAR(50) NOT NULL,
	EventTypeID INT FOREIGN KEY REFERENCES EVENT_TYPE(EventTypeID) NOT NULL,
	EventDescr VARCHAR(1000)
)
GO

CREATE TABLE ACKNOWLEDGEMENT(
	AckID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	EventID INT FOREIGN KEY REFERENCES EVENT(EventID) NOT NULL,
	RecipientID INT FOREIGN KEY REFERENCES USER_TEAM_ROLE(UserTeamRoleID) NOT NULL,
	DonorID INT FOREIGN KEY REFERENCES USER_TEAM_ROLE(UserTeamRoleID) NOT NULL,
	AckDate DATE NOT NULL,
	AckTime TIME NOT NULL,
	AckAmount Numeric(5,2) NOT NULL
)
GO

CREATE TABLE PRIZE_TYPE (
	PrizeTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	PrizeTypeName VARCHAR(50) NOT NULL,
	PrizeTypeDescr VARCHAR(1000) 
)
GO

CREATE TABLE PRIZE (
	PrizeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	PrizeName VARCHAR(50) NOT NULL,
	PrizeDate DATE NOT NULL,
	PrizeTypeID INT FOREIGN KEY REFERENCES PRIZE_TYPE(PrizeTypeID) NOT NULL,
	PrizeDescr VARCHAR(1000),
	PrizePoints numeric(5,0)
)
GO

CREATE TABLE REDEMPTION(
	RedemptionID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	PrizeID INT FOREIGN KEY REFERENCES PRIZE(PrizeID) NOT NULL,
	RedemptionName VARCHAR(50) NOT NULL,
	RedemptionDate DATE
)
GO

CREATE TABLE USER_TEAM_ROLE_REDEMPTION(
	UTRR_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	UserTeamRoleID INT FOREIGN KEY REFERENCES USER_TEAM_ROLE(UserTeamRoleID) NOT NULL,
	RedemptionID INT FOREIGN KEY REFERENCES REDEMPTION(RedemptionID) NOT NULL
)
GO
